version: '2'
services: 
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ekskul
    ports:
      - 9001:5432
    volumes:
      - ./db/db-data:/var/lib/posrgresql/data
